### ISSUE TITLE
Flow: Typing text in the notes is like roaming in the dark

### ISSUE THREAD

**Issue by henkvancann** [BlockchainCommons/GordianGuardian-iOS#38] opened 2021-02-28 11:37 UTC
Maybe possible to center the input field so you can see the action. Currently I have to use the scroll bar.
- [x] Add as an issue in github

🐺 @wolfmcnally : This is a [known upstream bug](https://github.com/BlockchainCommons/GordianGuardian-iOS/issues/1) that has been reported to Apple. I want to see whether they fix it relatively soon before implementing a hacky workaround. 

| ===|  | =========================== | 
|---| -------- | ------------------------ | 
| | ![](https://i.imgur.com/RMzmEIT.png)    | |

**Comment by wolfmcnally** [comment] 2021-03-02 08:19
Duplicate of #1.

**Closed by wolfmcnally** 2021-03-02 08:19 UTC
Labels: duplicate
