### ISSUE TITLE
Edit then optionally sort

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianGuardian-iOS#32] opened 2021-02-16 23:53 UTC
![EC5EC329-4BA5-4638-AF23-231644576300](https://user-images.githubusercontent.com/69103/108136462-f2f83b80-706e-11eb-9e29-d5ecaebf8a0c.png)

I like that I can edit and put the seed I use the most at top, but I’d really love a sort option here to use first, then adjust to move.

**Comment by wolfmcnally** [comment] 2021-02-18 00:39
Duplicate of #20.

**Closed** 2021-02-18 00:39 UTC
Labels: duplicate
